### ISSUE TITLE
chat issue

### ISSUE THREAD

**Issue by sethuraman17** [Conv-AI/RPM-Lipsync#1]
when i gtry to run this with npm start it opens without any problem but for speaking when i click t and release it it shows the error as 
Uncaught runtime errors:
×
ERROR
p is not a function
TypeError: p is not a function
    at http://localhost:3000/static/js/bundle.js:22198:34
    at http://localhost:3000/static/js/bundle.js:17449:21
    at Array.forEach (<anonymous>)
    at e.rawOnEnd (http://localhost:3000/static/js/bundle.js:17447:127)
    at e.onTransportEnd (http://localhost:3000/static/js/bundle.js:17436:24)
    at t.onclose (http://localhost:3000/static/js/bundle.js:17865:78)

**Comment by AirSurfer09** [comment]
This issue should be resolved now. Please check the setErrorCallback function in convai client file. it'll give you the grpc errors or network errors as reponse

**Comment by sethuraman17** [comment]
> This issue should be resolved now. Please check the setErrorCallback function in convai client file. it'll give you the grpc errors or network errors as reponse

hi, i have tried  again but still it is not working when i hold T and started speaking still it is not hearing

**Comment by AirSurfer09** [comment]
Does the errorCallback return any grpc error now?
